### ISSUE TITLE
对您的项目一些需求和一些问题的疑惑

### ISSUE THREAD

**Issue by FLY1919** [super1207/opqonebot#1]
支持的api太少了，没有完全发挥出opq真正实力，如果不介意的話，我十分希望你能支持更多api
如：收发红包，发送文件，获取pskey skey 
还有一些疑问，你的项目支持cq码吗(llntonebot不支持,对你这个项目造成疑惑)？我没有去实践，若有希望您制作出一个说明
是否与gocq无异？
希望你能解答
最后十分的感谢你能支持onebot v11

**Comment by super1207** [comment]
感谢使用！
这个项目会尽可能实现gocq支持的东西，文件上传暂时没做，但可以做。
红包，pskey，skey相关的内容不会支持，因为过于敏感，这方面的东西你可以通过直接对接opq的api来实现。
CQ码是支持的。
目前，readme里面的api，都是已经实现的，但某些api可能会缺失一些内容，如果opq的确可以获取到，你可以告诉我，我会修正。

**Comment by FLY1919** [comment]
> 感谢使用！ 这个项目会尽可能实现gocq支持的东西，文件上传暂时没做，但可以做。 红包，pskey，skey相关的内容不会支持，因为过于敏感，这方面的东西你可以通过直接对接opq的api来实现。 CQ码是支持的。 目前，readme里面的api，都是已经实现的，但某些api可能会缺失一些内容，如果opq的确可以获取到，你可以告诉我，我会修正。

>感谢解疑

**Comment by FLY1919** [comment]
> 感谢使用！ 这个项目会尽可能实现gocq支持的东西，文件上传暂时没做，但可以做。 红包，pskey，skey相关的内容不会支持，因为过于敏感，这方面的东西你可以通过直接对接opq的api来实现。 CQ码是支持的。 目前，readme里面的api，都是已经实现的，但某些api可能会缺失一些内容，如果opq的确可以获取到，你可以告诉我，我会修正。

感谢解疑,祝你新年快乐(✪▽✪)
