### ISSUE TITLE
OPQ更新点赞,markdown信息发送和合并信息发送

### ISSUE THREAD

**Issue by FLY1919** [super1207/opqonebot#3]
[发送群组MD消息](https://apifox.com/apidoc/shared-72cecf14-815e-4238-82a5-6c68d006fd00/api-160718990)

[上传组合消息](https://apifox.com/apidoc/shared-72cecf14-815e-4238-82a5-6c68d006fd00/api-164755333)

[点赞接口](https://apifox.com/apidoc/shared-72cecf14-815e-4238-82a5-6c68d006fd00/api-164885095)

你甚至不用自己找)

**Comment by FLY1919** [comment]
我操，还有一个设置头衔
[设置头衔](https://apifox.com/apidoc/shared-72cecf14-815e-4238-82a5-6c68d006fd00/api-147840439)

**Comment by super1207** [comment]
v0.1.4
设置头衔已经支持
上传组合消息已经支持(按gocq文档发送)
点赞已经支持

MD消息不支持，opq已经弃用
